### ISSUE TITLE
Errors when I try run the app

### ISSUE THREAD

**Issue by diogo10** [cemolcay/GiFHUD-Swift#1]
Hello, I just copy & paste GIFHUD.swift to my project....when I tried run shows these errors....

![screen shot 2015-07-31 at 15 19 38](https://cloud.githubusercontent.com/assets/1541244/9009219/99a0eb24-3797-11e5-92cb-7aa6e39bbb63.png)

**Comment by cemolcay** [comment]
hi, i updated the project, can you try this version ?

**Comment by diogo10** [comment]
worked like a charm @cemolcay......thanks =D
