### ISSUE TITLE
Build error: 'required' initializer 'init(imageLiteralResourceName:)' must be provided by subclass of 'UIImage'

### ISSUE THREAD

**Issue by thanhcuong1990** [cemolcay/GiFHUD-Swift#13]
I've got issue `'required' initializer 'init(imageLiteralResourceName:)' must be provided by subclass of 'UIImage'` after upgrade to Xcode 9.3

```
    required convenience init(imageLiteralResourceName name: String) {
        fatalError("init(imageLiteralResourceName:) has not been implemented")
    }
```
@cemolcay please help me take a look. Thanks!

**Comment by Nitinbond** [comment]
Overriding non-@objc declarations from extensions is not supported
'required' initializer 'init(imageLiteralResourceName:)' must be provided by subclass of 'UIImage'

can you resolve this ?

**Comment by Nitinbond** [comment]
I've got issue 'required' initializer 'init(imageLiteralResourceName:)' must be provided by subclass of 'UIImage' after upgrade to Xcode 9.3

    required convenience init(imageLiteralResourceName name: String) {
        fatalError("init(imageLiteralResourceName:) has not been implemented")
    }

**Comment by rajindervirk** [comment]
@Nitinbond 
Is there any solution for this ?

**Comment by rajindervirk** [comment]
Having same problem.
WTF with Swift 4.1 or Xcode 9.3.
Got stuck with this stupid issue..
Anyone please help me out.
Xcode keep showing error to add this after adding same method and @objc.

**Comment by sandeepan512** [comment]
Please override you method which is using extension name.
@rajindervirk

**Comment by Nitinbond** [comment]
can you send me your edited GiFHUD.swift file?

**Comment by Nitinbond** [comment]
Got some warnings: 
Conformance of 'UIImage' to protocol '_ExpressibleByImageLiteral' was already stated in the type's module 'UIKit'.
1. Initializer 'init(imageLiteralResourceName:)' will not be used to satisfy the conformance to '_ExpressibleByImageLiteral'

**Comment by rajindervirk** [comment]
https://www.dropbox.com/s/c1planvkkfgaepx/GiFHUD.swift?dl=0

**Comment by zeshanmusawar** [comment]
i got the same issue with xcode 9.3 
 required convenience init(imageLiteralResourceName name: String) {
        fatalError("init(imageLiteralResourceName:) has not been implemented")
    }

**Comment by Nitinbond** [comment]
Hello zeshanmusawr please contact me at skype: nitinbond@live.in

**Comment by cemolcay** [comment]
Hi guys, I did release a new version 0.3 just now. It's a 4 year old code. So many things changed in Swift world as well as my Swift skills. So, I just refactored all the code and make 
- GiFHUD -> GIFHUD, 
- GiFHUD.instance() -> GIFHUD.shared
- get rid off showWithOverlay etc functions and emit them one meaningful function with optional parameters
- AnimatableImage and UIImageView extension are gone, dedicated GIFHUDImage and GIFHUDImageView are doing the work now.
- Code organization is now better.
- Removed tap and swipe to dismiss functions. They are added by someone else and you can achieve this in your view controller, where it should be done.
- And updated readme
- Updated cocoapods (don't forget `pod update`)
- Swift 4.1 supported
